<?php
//服务器地址
define('DB_HOST','localhost');
//服务器端口
define('DB_PORT','3306');
//数据库类型
define('DB_TYPE','mysql');
//数据库用户名
define('DB_USER','payhy_8889s_com');
//数据库密码
define('DB_PASSWD','i3bBWCjc8Q');
//数据库名称
define('DB_NAME','payhy_8889s_com');
//数据库表名前缀
define('DB_PREFIX','vc_');
?>
